os: linux

language: python

python: 3.8

services:
  - docker

jobs:
  include:
    - os: linux
      dist: focal

branches:
  only:
    - proto
    - /^v\d+\.\d+\.\d+.*$/  # version tags

notifications:
  email:
    recipients:
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always

before_script:
  - openssl aes-256-cbc -K $encrypted_c72c54c8443e_key -iv $encrypted_c72c54c8443e_iv -in my.keystore.enc -out my.keystore -d
  - id -u 
  - id -g
  - echo "Travis tag is $TRAVIS_TAG"
  - bash travis/install_dependencies.bash

script: 
  - set -e
  - bash travis/build_client.bash 
  - bash travis/build_and_deploy_server.bash
  - bash travis/deploy_client.bash
  - set +e

# deploy:
#   provider: releases
#   user: $GH_USERNAME
#   password: $GH_TOKEN
#   file:
#     - build_output/xbot2_gui_client_android_arm64_v8a_signed.apk
#     - build_output/xbot2_gui_client_x86_64.zip
#   skip_cleanup: true
#   on:
#     tags: true