# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecat_pdo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_header_pb2 as msg__header__pb2
import esc_pdo_pb2 as esc__pdo__pb2
import generic_pb2 as generic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecat_pdo.proto',
  package='iit.advr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65\x63\x61t_pdo.proto\x12\x08iit.advr\x1a\x10msg_header.proto\x1a\resc_pdo.proto\x1a\rgeneric.proto\"\x98\x08\n\x0c\x45\x63_slave_pdo\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.iit.advr.Ec_slave_pdo.Type\x12 \n\x06header\x18\x02 \x01(\x0b\x32\x10.iit.advr.Header\x12*\n\x0cmotor_tx_pdo\x18\x05 \x01(\x0b\x32\x14.iit.advr.MotorTxPdo\x12*\n\x0cmotor_rx_pdo\x18\x06 \x01(\x0b\x32\x14.iit.advr.MotorRxPdo\x12&\n\nft6_tx_pdo\x18\x07 \x01(\x0b\x32\x12.iit.advr.FT6TxPdo\x12&\n\nft6_rx_pdo\x18\x08 \x01(\x0b\x32\x12.iit.advr.FT6RxPdo\x12*\n\x0cimuVN_rx_pdo\x18\x0f \x01(\x0b\x32\x14.iit.advr.ImuVNRxPdo\x12\x30\n\x0fheriHand_tx_pdo\x18\x11 \x01(\x0b\x32\x17.iit.advr.HeriHandTxPdo\x12\x30\n\x0fheriHand_rx_pdo\x18\x12 \x01(\x0b\x32\x17.iit.advr.HeriHandRxPdo\x12\x32\n\x10powF28M36_tx_pdo\x18\x13 \x01(\x0b\x32\x18.iit.advr.PowF28M36TxPdo\x12\x32\n\x10powF28M36_rx_pdo\x18\x14 \x01(\x0b\x32\x18.iit.advr.PowF28M36RxPdo\x12.\n\x0egeneric_tx_pdo\x18\x15 \x01(\x0b\x32\x16.iit.advr.GenericTxPdo\x12.\n\x0egeneric_rx_pdo\x18\x16 \x01(\x0b\x32\x16.iit.advr.GenericRxPdo\x12\x32\n\x10pressSens_tx_pdo\x18\x17 \x01(\x0b\x32\x18.iit.advr.PressSensTxPdo\x12\x32\n\x10pressSens_rx_pdo\x18\x18 \x01(\x0b\x32\x18.iit.advr.PressSensRxPdo\x12\"\n\tdummy_pdo\x18\x65 \x01(\x0b\x32\x0f.iit.advr.Dummy\x12(\n\nclient_pdo\x18o \x01(\x0b\x32\x14.iit.advr.ClientPipe\"\x84\x02\n\x04Type\x12\t\n\x05\x44UMMY\x10\x00\x12\n\n\x06RX_FT6\x10\x03\x12\n\n\x06TX_FT6\x10\x04\x12\x0c\n\x08RX_MOTOR\x10\t\x12\x0c\n\x08TX_MOTOR\x10\n\x12\r\n\tRX_IMU_VN\x10\x0f\x12\r\n\tTX_IMU_VN\x10\x10\x12\x10\n\x0cRX_HERI_HAND\x10\x13\x12\x10\n\x0cTX_HERI_HAND\x10\x14\x12\x11\n\rRX_POW_F28M36\x10\x15\x12\x11\n\rTX_POW_F28M36\x10\x16\x12\x0e\n\nRX_GENERIC\x10\x17\x12\x0e\n\nTX_GENERIC\x10\x18\x12\x11\n\rRX_PRESS_SENS\x10\x19\x12\x11\n\rTX_PRESS_SENS\x10\x1a\x12\x0f\n\x0b\x43LIENT_PIPE\x10ob\x06proto3'
  ,
  dependencies=[msg__header__pb2.DESCRIPTOR,esc__pdo__pb2.DESCRIPTOR,generic__pb2.DESCRIPTOR,])



_EC_SLAVE_PDO_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='iit.advr.Ec_slave_pdo.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_FT6', index=1, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_FT6', index=2, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_MOTOR', index=3, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_MOTOR', index=4, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_IMU_VN', index=5, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_IMU_VN', index=6, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_HERI_HAND', index=7, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_HERI_HAND', index=8, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_POW_F28M36', index=9, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_POW_F28M36', index=10, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_GENERIC', index=11, number=23,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_GENERIC', index=12, number=24,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RX_PRESS_SENS', index=13, number=25,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TX_PRESS_SENS', index=14, number=26,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_PIPE', index=15, number=111,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=865,
  serialized_end=1125,
)
_sym_db.RegisterEnumDescriptor(_EC_SLAVE_PDO_TYPE)


_EC_SLAVE_PDO = _descriptor.Descriptor(
  name='Ec_slave_pdo',
  full_name='iit.advr.Ec_slave_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='iit.advr.Ec_slave_pdo.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='iit.advr.Ec_slave_pdo.header', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_tx_pdo', full_name='iit.advr.Ec_slave_pdo.motor_tx_pdo', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_rx_pdo', full_name='iit.advr.Ec_slave_pdo.motor_rx_pdo', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ft6_tx_pdo', full_name='iit.advr.Ec_slave_pdo.ft6_tx_pdo', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ft6_rx_pdo', full_name='iit.advr.Ec_slave_pdo.ft6_rx_pdo', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imuVN_rx_pdo', full_name='iit.advr.Ec_slave_pdo.imuVN_rx_pdo', index=6,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heriHand_tx_pdo', full_name='iit.advr.Ec_slave_pdo.heriHand_tx_pdo', index=7,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heriHand_rx_pdo', full_name='iit.advr.Ec_slave_pdo.heriHand_rx_pdo', index=8,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powF28M36_tx_pdo', full_name='iit.advr.Ec_slave_pdo.powF28M36_tx_pdo', index=9,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powF28M36_rx_pdo', full_name='iit.advr.Ec_slave_pdo.powF28M36_rx_pdo', index=10,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generic_tx_pdo', full_name='iit.advr.Ec_slave_pdo.generic_tx_pdo', index=11,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generic_rx_pdo', full_name='iit.advr.Ec_slave_pdo.generic_rx_pdo', index=12,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pressSens_tx_pdo', full_name='iit.advr.Ec_slave_pdo.pressSens_tx_pdo', index=13,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pressSens_rx_pdo', full_name='iit.advr.Ec_slave_pdo.pressSens_rx_pdo', index=14,
      number=24, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dummy_pdo', full_name='iit.advr.Ec_slave_pdo.dummy_pdo', index=15,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_pdo', full_name='iit.advr.Ec_slave_pdo.client_pdo', index=16,
      number=111, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EC_SLAVE_PDO_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=1125,
)

_EC_SLAVE_PDO.fields_by_name['type'].enum_type = _EC_SLAVE_PDO_TYPE
_EC_SLAVE_PDO.fields_by_name['header'].message_type = msg__header__pb2._HEADER
_EC_SLAVE_PDO.fields_by_name['motor_tx_pdo'].message_type = esc__pdo__pb2._MOTORTXPDO
_EC_SLAVE_PDO.fields_by_name['motor_rx_pdo'].message_type = esc__pdo__pb2._MOTORRXPDO
_EC_SLAVE_PDO.fields_by_name['ft6_tx_pdo'].message_type = esc__pdo__pb2._FT6TXPDO
_EC_SLAVE_PDO.fields_by_name['ft6_rx_pdo'].message_type = esc__pdo__pb2._FT6RXPDO
_EC_SLAVE_PDO.fields_by_name['imuVN_rx_pdo'].message_type = esc__pdo__pb2._IMUVNRXPDO
_EC_SLAVE_PDO.fields_by_name['heriHand_tx_pdo'].message_type = esc__pdo__pb2._HERIHANDTXPDO
_EC_SLAVE_PDO.fields_by_name['heriHand_rx_pdo'].message_type = esc__pdo__pb2._HERIHANDRXPDO
_EC_SLAVE_PDO.fields_by_name['powF28M36_tx_pdo'].message_type = esc__pdo__pb2._POWF28M36TXPDO
_EC_SLAVE_PDO.fields_by_name['powF28M36_rx_pdo'].message_type = esc__pdo__pb2._POWF28M36RXPDO
_EC_SLAVE_PDO.fields_by_name['generic_tx_pdo'].message_type = generic__pb2._GENERICTXPDO
_EC_SLAVE_PDO.fields_by_name['generic_rx_pdo'].message_type = generic__pb2._GENERICRXPDO
_EC_SLAVE_PDO.fields_by_name['pressSens_tx_pdo'].message_type = esc__pdo__pb2._PRESSSENSTXPDO
_EC_SLAVE_PDO.fields_by_name['pressSens_rx_pdo'].message_type = esc__pdo__pb2._PRESSSENSRXPDO
_EC_SLAVE_PDO.fields_by_name['dummy_pdo'].message_type = generic__pb2._DUMMY
_EC_SLAVE_PDO.fields_by_name['client_pdo'].message_type = generic__pb2._CLIENTPIPE
_EC_SLAVE_PDO_TYPE.containing_type = _EC_SLAVE_PDO
DESCRIPTOR.message_types_by_name['Ec_slave_pdo'] = _EC_SLAVE_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ec_slave_pdo = _reflection.GeneratedProtocolMessageType('Ec_slave_pdo', (_message.Message,), {
  'DESCRIPTOR' : _EC_SLAVE_PDO,
  '__module__' : 'ecat_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Ec_slave_pdo)
  })
_sym_db.RegisterMessage(Ec_slave_pdo)


# @@protoc_insertion_point(module_scope)
