# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic.proto',
  package='iit.advr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgeneric.proto\x12\x08iit.advr\"5\n\x05\x44ummy\x12\x0e\n\x06vect_f\x18\x01 \x03(\x02\x12\x0f\n\x07vect_ui\x18\x02 \x03(\r\x12\x0b\n\x03rtt\x18\x03 \x01(\r\"b\n\x0cGenericRxPdo\x12\x0b\n\x03rtt\x18\x01 \x01(\r\x12\x12\n\nop_idx_ack\x18\x02 \x01(\r\x12\x0b\n\x03\x61ux\x18\x03 \x01(\x02\x12\x10\n\x08vect_int\x18\x04 \x03(\x03\x12\x12\n\nvect_float\x18\x05 \x03(\x02\";\n\x0cGenericTxPdo\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x12\n\nop_idx_aux\x18\x02 \x01(\r\x12\x0b\n\x03\x61ux\x18\x03 \x01(\x02\"T\n\nClientPipe\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.iit.advr.ClientPipe.Type\"\x1d\n\x04Type\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x08\n\x04QUIT\x10\x01\x62\x06proto3'
)



_CLIENTPIPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='iit.advr.ClientPipe.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=298,
  serialized_end=327,
)
_sym_db.RegisterEnumDescriptor(_CLIENTPIPE_TYPE)


_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='iit.advr.Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vect_f', full_name='iit.advr.Dummy.vect_f', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vect_ui', full_name='iit.advr.Dummy.vect_ui', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.Dummy.rtt', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=80,
)


_GENERICRXPDO = _descriptor.Descriptor(
  name='GenericRxPdo',
  full_name='iit.advr.GenericRxPdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.GenericRxPdo.rtt', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_idx_ack', full_name='iit.advr.GenericRxPdo.op_idx_ack', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.GenericRxPdo.aux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vect_int', full_name='iit.advr.GenericRxPdo.vect_int', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vect_float', full_name='iit.advr.GenericRxPdo.vect_float', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=180,
)


_GENERICTXPDO = _descriptor.Descriptor(
  name='GenericTxPdo',
  full_name='iit.advr.GenericTxPdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.GenericTxPdo.ts', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_idx_aux', full_name='iit.advr.GenericTxPdo.op_idx_aux', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.GenericTxPdo.aux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=241,
)


_CLIENTPIPE = _descriptor.Descriptor(
  name='ClientPipe',
  full_name='iit.advr.ClientPipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='iit.advr.ClientPipe.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTPIPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=327,
)

_CLIENTPIPE.fields_by_name['type'].enum_type = _CLIENTPIPE_TYPE
_CLIENTPIPE_TYPE.containing_type = _CLIENTPIPE
DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
DESCRIPTOR.message_types_by_name['GenericRxPdo'] = _GENERICRXPDO
DESCRIPTOR.message_types_by_name['GenericTxPdo'] = _GENERICTXPDO
DESCRIPTOR.message_types_by_name['ClientPipe'] = _CLIENTPIPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), {
  'DESCRIPTOR' : _DUMMY,
  '__module__' : 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Dummy)
  })
_sym_db.RegisterMessage(Dummy)

GenericRxPdo = _reflection.GeneratedProtocolMessageType('GenericRxPdo', (_message.Message,), {
  'DESCRIPTOR' : _GENERICRXPDO,
  '__module__' : 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.GenericRxPdo)
  })
_sym_db.RegisterMessage(GenericRxPdo)

GenericTxPdo = _reflection.GeneratedProtocolMessageType('GenericTxPdo', (_message.Message,), {
  'DESCRIPTOR' : _GENERICTXPDO,
  '__module__' : 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.GenericTxPdo)
  })
_sym_db.RegisterMessage(GenericTxPdo)

ClientPipe = _reflection.GeneratedProtocolMessageType('ClientPipe', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTPIPE,
  '__module__' : 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.ClientPipe)
  })
_sym_db.RegisterMessage(ClientPipe)


# @@protoc_insertion_point(module_scope)
