context:
  session: arturo
  params:
    verbose_flag: ''

roscore:
  cmd: ros1; roscore

ecat: 
  cmd: watch ls

wait_ecat_online: 
  cmd: watch ls

xbot2:
  cmd: ros1; xbot2-core --hw dummy -C $(rospack find kyon_config)/kyon_basic.yaml
  variants:
    verbose:
      params:
        verbose_flag: -V
  ready_check: timeout 3 rostopic echo /xbotcore/status -n 1

prova1:
  cmd: watch ls

prova2:
  cmd: watch ls