
cartesian:
  type: cartesian
  cmd_vel_topics:
  - /omnisteering/cmd_vel

launcher:
  type: launcher
  launcher_config: launcher_config.yaml

#horizon:
#  type: horizon  
#ecat_master_process:
#  type: process_handler
#  name: ecat_master
#  cmd: ecat_master
#  machine: embedded@10.24.4.100
#  rate: 1.0
