
cartesian:
  type: cartesian
  cmd_vel_topics:
  - /omnisteering/cmd_vel

launcher:
  type: launcher
  launcher_config: launcher_config.yaml

concert:
  type: concert
  sanding_tool_activated_service: ciao
  blob_array_topic: ciaoo
  sanding_status_topic: ciaooo
  sanding_progress_topic: ciaoooo

#speech:
#  prompt: hey concert 
#  commands:
#    teaching: /voice_commands/teaching
#    lift: /voice_commands/lift
#    transportation: /voice_commands/transportation
#    autonomous: adssdd
#    close gripper: cg
#    open gripper: og

speech:
  prompt: hey concert
  commands: 
    state:
      autonomous: /coworker_supervisor/start_autonomous
      teaching: /coworker_supervisor/start_teaching
      follow: /coworker_supervisor/start_ffm
      stop: /coworker_supervisor/abort
    task:
      lift: /coworker_supervisor/move_arm_up
      place: /coworker_supervisor/move_arm_down
      open: /coworker_supervisor/open_gripper
      close: /coworker_supervisor/close_gripper
  state_task_map: # mapping between state and allowed tasks
    autonomous: [lift, place]
    teaching: [open, close, lift]
    follow: [place]
#horizon:
#  type: horizon  
#ecat_master_process:
#  type: process_handler
#  name: ecat_master
#  cmd: ecat_master
#  machine: embedded@10.24.4.100
#  rate: 1.0
