
cartesian:
  type: cartesian
  cmd_vel_topics:
  - /omnisteering/cmd_vel

launcher:
  type: launcher
  launcher_config: launcher_config.yaml

concert:
  type: concert
  sanding_tool_activated_service: ciao
  blob_array_topic: ciaoo
  sanding_status_topic: ciaooo
  sanding_progress_topic: ciaoooo

speech:
  prompt: hey concert 
  commands:
    teaching: /voice_commands/teaching
    lift: /voice_commands/lift
    transportation: /voice_commands/transportation

#horizon:
#  type: horizon  
#ecat_master_process:
#  type: process_handler
#  name: ecat_master
#  cmd: ecat_master
#  machine: embedded@10.24.4.100
#  rate: 1.0
