# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jointstate_pb2 as jointstate__pb2
import text_pb2 as text__pb2
import process_output_pb2 as process__output__pb2
import theora_packet_pb2 as theora__packet__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneric.proto\x1a\x10jointstate.proto\x1a\ntext.proto\x1a\x14process_output.proto\x1a\x13theora_packet.proto\"\x9a\x01\n\x07Message\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x1f\n\njointstate\x18\x02 \x01(\x0b\x32\x0b.JointState\x12\x13\n\x04text\x18\x03 \x01(\x0b\x32\x05.Text\x12&\n\x0eprocess_output\x18\x04 \x01(\x0b\x32\x0e.ProcessOutput\x12$\n\rtheora_packet\x18\x05 \x01(\x0b\x32\r.TheoraPacketb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=91
  _MESSAGE._serialized_end=245
# @@protoc_insertion_point(module_scope)
