# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: theora_packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13theora_packet.proto\"u\n\x0cTheoraPacket\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05\x62_o_s\x18\x03 \x01(\x05\x12\r\n\x05\x65_o_s\x18\x04 \x01(\x05\x12\x12\n\ngranulepos\x18\x05 \x01(\x05\x12\x10\n\x08packetno\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'theora_packet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THEORAPACKET._serialized_start=23
  _THEORAPACKET._serialized_end=140
# @@protoc_insertion_point(module_scope)
