FROM arturolaurenzi/qt6dev:latest

COPY --chown=1000:1000 context/robot_monitoring /home/user/robot_monitoring
COPY --chown=1000:1000 context/robot_monitoring/travis/docker/build.bash /home/user/build.bash