# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joint_states.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='joint_states.proto',
  package='xbot2_gui.msgs.joint_states',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12joint_states.proto\x12\x1bxbot2_gui.msgs.joint_states\"[\n\x0bJointStates\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x16\n\x0emotor_position\x18\x02 \x03(\x02\x12\x16\n\x0emotor_velocity\x18\x03 \x03(\x02\x12\x0e\n\x06\x65\x66\x66ort\x18\x04 \x03(\x02\x62\x06proto3')
)




_JOINTSTATES = _descriptor.Descriptor(
  name='JointStates',
  full_name='xbot2_gui.msgs.joint_states.JointStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='xbot2_gui.msgs.joint_states.JointStates.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_position', full_name='xbot2_gui.msgs.joint_states.JointStates.motor_position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_velocity', full_name='xbot2_gui.msgs.joint_states.JointStates.motor_velocity', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effort', full_name='xbot2_gui.msgs.joint_states.JointStates.effort', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['JointStates'] = _JOINTSTATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointStates = _reflection.GeneratedProtocolMessageType('JointStates', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATES,
  __module__ = 'joint_states_pb2'
  # @@protoc_insertion_point(class_scope:xbot2_gui.msgs.joint_states.JointStates)
  ))
_sym_db.RegisterMessage(JointStates)


# @@protoc_insertion_point(module_scope)
