# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tlv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tlv.proto',
  package='xbot2_gui.msgs.tlv',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ttlv.proto\x12\x12xbot2_gui.msgs.tlv\"J\n\nTlvMessage\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.xbot2_gui.msgs.tlv.MessageType\x12\r\n\x05value\x18\x02 \x01(\x0c*H\n\x0bMessageType\x12\x0f\n\x0b\x43oordinates\x10\x00\x12\x0f\n\x0bTemperature\x10\x01\x12\x17\n\x13WarningNotification\x10\x02\x62\x06proto3')
)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='xbot2_gui.msgs.tlv.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Coordinates', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Temperature', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningNotification', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=109,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
Coordinates = 0
Temperature = 1
WarningNotification = 2



_TLVMESSAGE = _descriptor.Descriptor(
  name='TlvMessage',
  full_name='xbot2_gui.msgs.tlv.TlvMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='xbot2_gui.msgs.tlv.TlvMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='xbot2_gui.msgs.tlv.TlvMessage.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=107,
)

_TLVMESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
DESCRIPTOR.message_types_by_name['TlvMessage'] = _TLVMESSAGE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TlvMessage = _reflection.GeneratedProtocolMessageType('TlvMessage', (_message.Message,), dict(
  DESCRIPTOR = _TLVMESSAGE,
  __module__ = 'tlv_pb2'
  # @@protoc_insertion_point(class_scope:xbot2_gui.msgs.tlv.TlvMessage)
  ))
_sym_db.RegisterMessage(TlvMessage)


# @@protoc_insertion_point(module_scope)
