name: Build Linux and Android

on:
  push:
    branches: [ "2.0-master", "wasm_devel" ]
  pull_request:
    branches: [ "2.0-master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Retrieve the secret and decode it to a file
      env:
        MY_KEYSTORE_BASE64: ${{ secrets.MY_KEYSTORE_BASE64 }}
      run: |
        echo $MY_KEYSTORE_BASE64 | base64 --decode > my.keystore
    - name: Install dependencies
      run: bash travis/install_dependencies.bash
    - name: Build client
      env:
        KEYSTORE_PWD: ${{ secrets.KEYSTORE_PWD }}
      run: bash travis/build_client.bash
    - name: Build server
      run: bash travis/build_and_deploy_server.bash
